# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buckets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftRangeSlider', '~> 1.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ActionCableClient'
    
  pod 'SwiftWebSocket'
  
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  
  
  
  pod 'JSQMessagesViewController'
 pod 'Parse'
pod 'Backendless'

end
